In [1]:
from keras import Sequential

c:\Users\KIIT0001\Desktop\Deep_learning\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
from keras.layers import Dense,SimpleRNN

In [5]:
model = Sequential()

model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

model.summary()

c:\Users\KIIT0001\Desktop\Deep_learning\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[-0.00630581,  0.7407147 ,  0.53228575],
       [ 0.60220534, -0.6634634 ,  0.33179587],
       [ 0.64030486,  0.19936818, -0.58523715],
       [-0.38139665,  0.24008244,  0.8204573 ],
       [-0.14202219, -0.6407857 ,  0.83439404]], dtype=float32)

In [7]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.42825592, -0.30188343, -0.8517412 ],
       [-0.04259093,  0.94824445, -0.31467235],
       [ 0.90265316, -0.09848388, -0.41894883]], dtype=float32)

In [8]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [9]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[-0.5457966 ],
       [ 0.3937608 ],
       [ 0.34029877]], dtype=float32)